# Pandas For Data Manipulation, Analysis and Preparation

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## Loading Our Data into Pandas Data Frame

In [2]:
# Import our Data into a Data Frame
df = pd.read_csv(r"C:\Users\User\desktop\Python-Class\Data\homelessness.csv")

# The 'r' here views it as a raw string

## Exploring Our Data

In [3]:
# Viewing the first 5 Rows of the Data Frame
df.head()

# If we don't add any number inside the brackets then it will pass the first 5

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [4]:
# Viewing the last 5 Rows of the Data Frame
df.tail()

# df.tail(10) will pass the last 10 rows

,Unnamed: 0,region,state,individuals,family_members,state_pop
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [5]:
# Get Dataset Information
df.info()

# `non-null` here means that all entires are filled, there are no empty values

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     str
 2   state           51 non-null     str
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 2.5 KB

In [6]:
# Getting the Number of rows and columns in my dataframe in this case 51 rows and 6 columns
df.shape

(51, 6)

In [7]:
# Getting the summary statistics of the dataset
df.describe()

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

In [8]:
df.values

array([[0, 'East South Central', 'Alabama', 2570.0, 864.0, 4887681],
       [1, 'Pacific', 'Alaska', 1434.0, 582.0, 735139],
       [2, 'Mountain', 'Arizona', 7259.0, 2606.0, 7158024],
       [3, 'West South Central', 'Arkansas', 2280.0, 432.0, 3009733],
       [4, 'Pacific', 'California', 109008.0, 20964.0, 39461588],
       [5, 'Mountain', 'Colorado', 7607.0, 3250.0, 5691287],
       [6, 'New England', 'Connecticut', 2280.0, 1696.0, 3571520],
       [7, 'South Atlantic', 'Delaware', 708.0, 374.0, 965479],
       [8, 'South Atlantic', 'District of Columbia', 3770.0, 3134.0,
        701547],
       [9, 'South Atlantic', 'Florida', 21443.0, 9587.0, 21244317],
       [10, 'South Atlantic', 'Georgia', 6943.0, 2556.0, 10511131],
       [11, 'Pacific', 'Hawaii', 4131.0, 2399.0, 1420593],
       [12, 'Mountain', 'Idaho', 1297.0, 715.0, 1750536],
       [13, 'East North Central', 'Illinois', 6752.0, 3891.0, 12723071],
       [14, 'East North Central', 'Indiana', 3776.0, 1482.0, 6695497],
       [15, 'West North Central', 'Iowa', 1711.0, 1038.0, 3148618],
       [16, 'West North Central', 'Kansas', 1443.0, 773.0, 2911359],
       [17, 'East South Central', 'Kentucky', 2735.0, 953.0, 4461153],
       [18, 'West South Central', 'Louisiana', 2540.0, 519.0, 4659690],
       [19, 'New England', 'Maine', 1450.0, 1066.0, 1339057],
       [20, 'South Atlantic', 'Maryland', 4914.0, 2230.0, 6035802],
       [21, 'New England', 'Massachusetts', 6811.0, 13257.0, 6882635],
       [22, 'East North Central', 'Michigan', 5209.0, 3142.0, 9984072],
       [23, 'West North Central', 'Minnesota', 3993.0, 3250.0, 5606249],
       [24, 'East South Central', 'Mississippi', 1024.0, 328.0, 2981020],
       [25, 'West North Central', 'Missouri', 3776.0, 2107.0, 6121623],
       [26, 'Mountain', 'Montana', 983.0, 422.0, 1060665],
       [27, 'West North Central', 'Nebraska', 1745.0, 676.0, 1925614],
       [28, 'Mountain', 'Nevada', 7058.0, 486.0, 3027341],
       [29, 'New England', 'New Hampshire', 835.0, 615.0, 1353465],
       [30, 'Mid-Atlantic', 'New Jersey', 6048.0, 3350.0, 8886025],
       [31, 'Mountain', 'New Mexico', 1949.0, 602.0, 2092741],
       [32, 'Mid-Atlantic', 'New York', 39827.0, 52070.0, 19530351],
       [33, 'South Atlantic', 'North Carolina', 6451.0, 2817.0, 10381615],
       [34, 'West North Central', 'North Dakota', 467.0, 75.0, 758080],
       [35, 'East North Central', 'Ohio', 6929.0, 3320.0, 11676341],
       [36, 'West South Central', 'Oklahoma', 2823.0, 1048.0, 3940235],
       [37, 'Pacific', 'Oregon', 11139.0, 3337.0, 4181886],
       [38, 'Mid-Atlantic', 'Pennsylvania', 8163.0, 5349.0, 12800922],
       [39, 'New England', 'Rhode Island', 747.0, 354.0, 1058287],
       [40, 'South Atlantic', 'South Carolina', 3082.0, 851.0, 5084156],
       [41, 'West North Central', 'South Dakota', 836.0, 323.0, 878698],
       [42, 'East South Central', 'Tennessee', 6139.0, 1744.0, 6771631],
       [43, 'West South Central', 'Texas', 19199.0, 6111.0, 28628666],
       [44, 'Mountain', 'Utah', 1904.0, 972.0, 3153550],
       [45, 'New England', 'Vermont', 780.0, 511.0, 624358],
       [46, 'South Atlantic', 'Virginia', 3928.0, 2047.0, 8501286],
       [47, 'Pacific', 'Washington', 16424.0, 5880.0, 7523869],
       [48, 'South Atlantic', 'West Virginia', 1021.0, 222.0, 1804291],
       [49, 'East North Central', 'Wisconsin', 2740.0, 2167.0, 5807406],
       [50, 'Mountain', 'Wyoming', 434.0, 205.0, 577601]], dtype=object)

In [9]:
df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='str')

In [10]:
df.index

# step size = 1
# from start = `0` to stop = `51` we take a step of 1

RangeIndex(start=0, stop=51, step=1)

## Data Cleaning

- Deleting the `Unnamed: 0` since its just a duplicate of the index column

In [11]:
# drop the `Unnamed: 0' column from the DataFrame
df = df.drop(columns="Unnamed: 0")

In [12]:
df.columns

Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='str')

# Sorting and Subsetting in Pandas

### Sorting Values

In [13]:
df.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [14]:
# Sorting the Data Fram by the `state_pop` column in ascending order
df.sort_values("state_pop")

,region,state,individuals,family_members,state_pop
50,Mountain,Wyoming,434.0,205.0,577601
45,New England,Vermont,780.0,511.0,624358
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
1,Pacific,Alaska,1434.0,582.0,735139
34,West North Central,North Dakota,467.0,75.0,758080
41,West North Central,South Dakota,836.0,323.0,878698
7,South Atlantic,Delaware,708.0,374.0,965479
39,New England,Rhode Island,747.0,354.0,1058287
26,Mountain,Montana,983.0,422.0,1060665
19,New England,Maine,1450.0,1066.0,1339057
29,New England,New Hampshire,835.0,615.0,1353465
11,Pacific,Hawaii,4131.0,2399.0,1420593
12,Mountain,Idaho,1297.0,715.0,1750536
48,South Atlantic,West Virginia,1021.0,222.0,1804291
27,West North Central,Nebraska,1745.0,676.0,1925614
31,Mountain,New Mexico,1949.0,602.0,2092741
16,West North Central,Kansas,1443.0,773.0,2911359
24,East South Central,Mississippi,1024.0,328.0,2981020
3,West South Central,Arkansas,2280.0,432.0,3009733
28,Mountain,Nevada,7058.0,486.0,3027341
15,West North Central,Iowa,1711.0,1038.0,3148618
44,Mountain,Utah,1904.0,972.0,3153550
6,New England,Connecticut,2280.0,1696.0,3571520
36,West South Central,Oklahoma,2823.0,1048.0,3940235
37,Pacific,Oregon,11139.0,3337.0,4181886
17,East South Central,Kentucky,2735.0,953.0,4461153
18,West South Central,Louisiana,2540.0,519.0,4659690
0,East South Central,Alabama,2570.0,864.0,4887681
40,South Atlantic,South Carolina,3082.0,851.0,5084156
23,West North Central,Minnesota,3993.0,3250.0,5606249
5,Mountain,Colorado,7607.0,3250.0,5691287
49,East North Central,Wisconsin,2740.0,2167.0,5807406
20,South Atlantic,Maryland,4914.0,2230.0,6035802
25,West North Central,Missouri,3776.0,2107.0,6121623
14,East North Central,Indiana,3776.0,1482.0,6695497
42,East South Central,Tennessee,6139.0,1744.0,6771631
21,New England,Massachusetts,6811.0,13257.0,6882635
2,Mountain,Arizona,7259.0,2606.0,7158024
47,Pacific,Washington,16424.0,5880.0,7523869
46,South Atlantic,Virginia,3928.0,2047.0,8501286
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
22,East North Central,Michigan,5209.0,3142.0,9984072
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
10,South Atlantic,Georgia,6943.0,2556.0,10511131
35,East North Central,Ohio,6929.0,3320.0,11676341
13,East North Central,Illinois,6752.0,3891.0,12723071
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
9,South Atlantic,Florida,21443.0,9587.0,21244317
43,West South Central,Texas,19199.0,6111.0,28628666
4,Pacific,California,109008.0,20964.0,39461588

In [15]:
# Sorting the Data Fram by the `state_pop` column in descending order
df.sort_values("state_pop", ascending=False)

,region,state,individuals,family_members,state_pop
4,Pacific,California,109008.0,20964.0,39461588
43,West South Central,Texas,19199.0,6111.0,28628666
9,South Atlantic,Florida,21443.0,9587.0,21244317
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
13,East North Central,Illinois,6752.0,3891.0,12723071
35,East North Central,Ohio,6929.0,3320.0,11676341
10,South Atlantic,Georgia,6943.0,2556.0,10511131
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
22,East North Central,Michigan,5209.0,3142.0,9984072
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,Pacific,Washington,16424.0,5880.0,7523869
2,Mountain,Arizona,7259.0,2606.0,7158024
21,New England,Massachusetts,6811.0,13257.0,6882635
42,East South Central,Tennessee,6139.0,1744.0,6771631
14,East North Central,Indiana,3776.0,1482.0,6695497
25,West North Central,Missouri,3776.0,2107.0,6121623
20,South Atlantic,Maryland,4914.0,2230.0,6035802
49,East North Central,Wisconsin,2740.0,2167.0,5807406
5,Mountain,Colorado,7607.0,3250.0,5691287
23,West North Central,Minnesota,3993.0,3250.0,5606249
40,South Atlantic,South Carolina,3082.0,851.0,5084156
0,East South Central,Alabama,2570.0,864.0,4887681
18,West South Central,Louisiana,2540.0,519.0,4659690
17,East South Central,Kentucky,2735.0,953.0,4461153
37,Pacific,Oregon,11139.0,3337.0,4181886
36,West South Central,Oklahoma,2823.0,1048.0,3940235
6,New England,Connecticut,2280.0,1696.0,3571520
44,Mountain,Utah,1904.0,972.0,3153550
15,West North Central,Iowa,1711.0,1038.0,3148618
28,Mountain,Nevada,7058.0,486.0,3027341
3,West South Central,Arkansas,2280.0,432.0,3009733
24,East South Central,Mississippi,1024.0,328.0,2981020
16,West North Central,Kansas,1443.0,773.0,2911359
31,Mountain,New Mexico,1949.0,602.0,2092741
27,West North Central,Nebraska,1745.0,676.0,1925614
48,South Atlantic,West Virginia,1021.0,222.0,1804291
12,Mountain,Idaho,1297.0,715.0,1750536
11,Pacific,Hawaii,4131.0,2399.0,1420593
29,New England,New Hampshire,835.0,615.0,1353465
19,New England,Maine,1450.0,1066.0,1339057
26,Mountain,Montana,983.0,422.0,1060665
39,New England,Rhode Island,747.0,354.0,1058287
7,South Atlantic,Delaware,708.0,374.0,965479
41,West North Central,South Dakota,836.0,323.0,878698
34,West North Central,North Dakota,467.0,75.0,758080
1,Pacific,Alaska,1434.0,582.0,735139
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
45,New England,Vermont,780.0,511.0,624358
50,Mountain,Wyoming,434.0,205.0,577601

**Sorting by Multiple Variables**

In [16]:
df.sort_values(["state_pop", "family_members"], ascending = [False, False])

,region,state,individuals,family_members,state_pop
4,Pacific,California,109008.0,20964.0,39461588
43,West South Central,Texas,19199.0,6111.0,28628666
9,South Atlantic,Florida,21443.0,9587.0,21244317
32,Mid-Atlantic,New York,39827.0,52070.0,19530351
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
13,East North Central,Illinois,6752.0,3891.0,12723071
35,East North Central,Ohio,6929.0,3320.0,11676341
10,South Atlantic,Georgia,6943.0,2556.0,10511131
33,South Atlantic,North Carolina,6451.0,2817.0,10381615
22,East North Central,Michigan,5209.0,3142.0,9984072
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,Pacific,Washington,16424.0,5880.0,7523869
2,Mountain,Arizona,7259.0,2606.0,7158024
21,New England,Massachusetts,6811.0,13257.0,6882635
42,East South Central,Tennessee,6139.0,1744.0,6771631
14,East North Central,Indiana,3776.0,1482.0,6695497
25,West North Central,Missouri,3776.0,2107.0,6121623
20,South Atlantic,Maryland,4914.0,2230.0,6035802
49,East North Central,Wisconsin,2740.0,2167.0,5807406
5,Mountain,Colorado,7607.0,3250.0,5691287
23,West North Central,Minnesota,3993.0,3250.0,5606249
40,South Atlantic,South Carolina,3082.0,851.0,5084156
0,East South Central,Alabama,2570.0,864.0,4887681
18,West South Central,Louisiana,2540.0,519.0,4659690
17,East South Central,Kentucky,2735.0,953.0,4461153
37,Pacific,Oregon,11139.0,3337.0,4181886
36,West South Central,Oklahoma,2823.0,1048.0,3940235
6,New England,Connecticut,2280.0,1696.0,3571520
44,Mountain,Utah,1904.0,972.0,3153550
15,West North Central,Iowa,1711.0,1038.0,3148618
28,Mountain,Nevada,7058.0,486.0,3027341
3,West South Central,Arkansas,2280.0,432.0,3009733
24,East South Central,Mississippi,1024.0,328.0,2981020
16,West North Central,Kansas,1443.0,773.0,2911359
31,Mountain,New Mexico,1949.0,602.0,2092741
27,West North Central,Nebraska,1745.0,676.0,1925614
48,South Atlantic,West Virginia,1021.0,222.0,1804291
12,Mountain,Idaho,1297.0,715.0,1750536
11,Pacific,Hawaii,4131.0,2399.0,1420593
29,New England,New Hampshire,835.0,615.0,1353465
19,New England,Maine,1450.0,1066.0,1339057
26,Mountain,Montana,983.0,422.0,1060665
39,New England,Rhode Island,747.0,354.0,1058287
7,South Atlantic,Delaware,708.0,374.0,965479
41,West North Central,South Dakota,836.0,323.0,878698
34,West North Central,North Dakota,467.0,75.0,758080
1,Pacific,Alaska,1434.0,582.0,735139
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
45,New England,Vermont,780.0,511.0,624358
50,Mountain,Wyoming,434.0,205.0,577601

#### Concatination

In [17]:
df1 = df[:5]
df1

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [18]:
df2 = df[5:10]
df2

,region,state,individuals,family_members,state_pop
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [19]:
all_data = pd.concat([df1, df2])
all_data

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [20]:
all_data = pd.concat([df1, df2], axis=0)
all_data

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681
1,Pacific,Alaska,1434.0,582.0,735139
2,Mountain,Arizona,7259.0,2606.0,7158024
3,West South Central,Arkansas,2280.0,432.0,3009733
4,Pacific,California,109008.0,20964.0,39461588
5,Mountain,Colorado,7607.0,3250.0,5691287
6,New England,Connecticut,2280.0,1696.0,3571520
7,South Atlantic,Delaware,708.0,374.0,965479
8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,South Atlantic,Florida,21443.0,9587.0,21244317

In [21]:
all_data = pd.concat([df1, df2], axis=1)
all_data

,region,state,individuals,family_members,state_pop,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570.0,864.0,4887681.0,NaN,NaN,NaN,NaN,NaN
1,Pacific,Alaska,1434.0,582.0,735139.0,NaN,NaN,NaN,NaN,NaN
2,Mountain,Arizona,7259.0,2606.0,7158024.0,NaN,NaN,NaN,NaN,NaN
3,West South Central,Arkansas,2280.0,432.0,3009733.0,NaN,NaN,NaN,NaN,NaN
4,Pacific,California,109008.0,20964.0,39461588.0,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,Mountain,Colorado,7607.0,3250.0,5691287.0
6,NaN,NaN,NaN,NaN,NaN,New England,Connecticut,2280.0,1696.0,3571520.0
7,NaN,NaN,NaN,NaN,NaN,South Atlantic,Delaware,708.0,374.0,965479.0
8,NaN,NaN,NaN,NaN,NaN,South Atlantic,District of Columbia,3770.0,3134.0,701547.0
9,NaN,NaN,NaN,NaN,NaN,South Atlantic,Florida,21443.0,9587.0,21244317.0

#### Combining Datasets Merge and join

In [22]:
state_capital = pd.DataFrame(
    {
        "state": ["California", "Texas", "New York"],
        "captial": ["Sacramento", "Austin", "Albany"]
    }
)

In [23]:
state_capital.head()

        state     captial
0  California  Sacramento
1       Texas      Austin
2    New York      Albany

In [24]:
df.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [25]:
merged_df = pd.merge(df, state_capital, on="state")

In [26]:
state_senators = pd.DataFrame(
    {
        "state": ["California", "Texas", "New York"],
        "senators": ["Alex Padilla", "John Cornyn", "Chuck Schumer"]
    }
)

In [27]:
merged_senators_df = pd.merge(df, state_senators, on="state")

In [28]:
merged_senators_df.head()

,region,state,individuals,family_members,state_pop,senators
0,Pacific,California,109008.0,20964.0,39461588,Alex Padilla
1,Mid-Atlantic,New York,39827.0,52070.0,19530351,Chuck Schumer
2,West South Central,Texas,19199.0,6111.0,28628666,John Cornyn

**Adding New Columns**

In [29]:
df.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [30]:
df["total_homeless"] = df["individuals"] + df["family_members"]
df.head()

,region,state,individuals,family_members,state_pop,total_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0
1,Pacific,Alaska,1434.0,582.0,735139,2016.0
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0
4,Pacific,California,109008.0,20964.0,39461588,129972.0

In [31]:
df["pct_homeless"] = (df["total_homeless"] / df["state_pop"]) * 100

In [32]:
df.head()

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363

### Subsetting DataFrames and Multiple Calculations

In [33]:
state_and_total_only = df[["state", "total_homeless"]]

In [34]:
gt10k_homeless = state_and_total_only[state_and_total_only["total_homeless"] > 10000]
gt10k_homeless

            state  total_homeless
4      California        129972.0
5        Colorado         10857.0
9         Florida         31030.0
13       Illinois         10643.0
21  Massachusetts         20068.0
32       New York         91897.0
35           Ohio         10249.0
37         Oregon         14476.0
38   Pennsylvania         13512.0
43          Texas         25310.0
47     Washington         22304.0

In [35]:
no_index_gt10k = gt10k_homeless.reset_index(drop=True)
no_index_gt10k

            state  total_homeless
0      California        129972.0
1        Colorado         10857.0
2         Florida         31030.0
3        Illinois         10643.0
4   Massachusetts         20068.0
5        New York         91897.0
6            Ohio         10249.0
7          Oregon         14476.0
8    Pennsylvania         13512.0
9           Texas         25310.0
10     Washington         22304.0

## Explicit Indexing

In [36]:
dfcopy = df.copy()

In [37]:
dfcopy.head()

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
0,East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
1,Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
3,West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
4,Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363

In [38]:
#.columns and .index
dfcopy.columns

Index(['region', 'state', 'individuals', 'family_members', 'state_pop',
       'total_homeless', 'pct_homeless'],
      dtype='str')

In [39]:
dfcopy.index

RangeIndex(start=0, stop=51, step=1)

In [40]:
# checking for duplicates in the state column and get the number of duplicates in the state column
dfcopy["state"].duplicated().sum()

np.int64(0)

#### Setting a column as the Index

In [41]:
dfindex = dfcopy.set_index("state")
dfindex.head()

,region,individuals,family_members,state_pop,total_homeless,pct_homeless
state,,,,,,
Alabama,East South Central,2570.0,864.0,4887681,3434.0,0.070258
Alaska,Pacific,1434.0,582.0,735139,2016.0,0.274234
Arizona,Mountain,7259.0,2606.0,7158024,9865.0,0.137817
Arkansas,West South Central,2280.0,432.0,3009733,2712.0,0.090108
California,Pacific,109008.0,20964.0,39461588,129972.0,0.329363

- Filter the data to only show the details of homeless people in Arizona, Nevada, Texas and Utah

In [42]:
# If we use our original dataframe to do this here is how
df[df["state"].isin(["Arizona", "Texas", "Nevada", "Utah"])]

,region,state,individuals,family_members,state_pop,total_homeless,pct_homeless
2,Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
28,Mountain,Nevada,7058.0,486.0,3027341,7544.0,0.249196
43,West South Central,Texas,19199.0,6111.0,28628666,25310.0,0.088408
44,Mountain,Utah,1904.0,972.0,3153550,2876.0,0.091199

In [43]:
# Subsetting gets easy when the column state is made an index
dfindex.loc[["Arizona", "Texas", "Nevada", "Utah"]]

,region,individuals,family_members,state_pop,total_homeless,pct_homeless
state,,,,,,
Arizona,Mountain,7259.0,2606.0,7158024,9865.0,0.137817
Texas,West South Central,19199.0,6111.0,28628666,25310.0,0.088408
Nevada,Mountain,7058.0,486.0,3027341,7544.0,0.249196
Utah,Mountain,1904.0,972.0,3153550,2876.0,0.091199

**Index Values don't need to be unique**

- This means you can have a column with duplicate values as the index column

In [44]:
dfcopy["region"].duplicated().sum()

np.int64(42)

In [45]:
dfDuplicateIndex = dfcopy.set_index("region")
dfDuplicateIndex.head()

,state,individuals,family_members,state_pop,total_homeless,pct_homeless
region,,,,,,
East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363

In [46]:
# Subsetting on duplicated index
dfDuplicateIndex.loc["Pacific"]

,state,individuals,family_members,state_pop,total_homeless,pct_homeless
region,,,,,,
Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363
Pacific,Hawaii,4131.0,2399.0,1420593,6530.0,0.459667
Pacific,Oregon,11139.0,3337.0,4181886,14476.0,0.346160
Pacific,Washington,16424.0,5880.0,7523869,22304.0,0.296443

### Multi-level Indexes / Heiratical Indexes

- Using multiple columns as you index

In [47]:
df_ind3 = dfcopy.set_index(["region", "state"])
df_ind3.head()

,,individuals,family_members,state_pop,total_homeless,pct_homeless
region,state,,,,,
East South Central,Alabama,2570.0,864.0,4887681,3434.0,0.070258
Pacific,Alaska,1434.0,582.0,735139,2016.0,0.274234
Mountain,Arizona,7259.0,2606.0,7158024,9865.0,0.137817
West South Central,Arkansas,2280.0,432.0,3009733,2712.0,0.090108
Pacific,California,109008.0,20964.0,39461588,129972.0,0.329363

In [48]:
# Zack's way for subsetting df_ind3
idx = pd.IndexSlice
df_ind3.loc[idx[["Pacific", "Mountain"], :], :]

                     individuals  family_members  state_pop  total_homeless  \
region   state
Pacific  Alaska           1434.0           582.0     735139          2016.0
         California     109008.0         20964.0   39461588        129972.0
         Hawaii           4131.0          2399.0    1420593          6530.0
         Oregon          11139.0          3337.0    4181886         14476.0
         Washington      16424.0          5880.0    7523869         22304.0
Mountain Arizona          7259.0          2606.0    7158024          9865.0
         Colorado         7607.0          3250.0    5691287         10857.0
         Idaho            1297.0           715.0    1750536          2012.0
         Montana           983.0           422.0    1060665          1405.0
         Nevada           7058.0           486.0    3027341          7544.0
         New Mexico       1949.0           602.0    2092741          2551.0
         Utah             1904.0           972.0    3153550          2876.0
         Wyoming           434.0           205.0     577601           639.0

                     pct_homeless
region   state
Pacific  Alaska          0.274234
         California      0.329363
         Hawaii          0.459667
         Oregon          0.346160
         Washington      0.296443
Mountain Arizona         0.137817
         Colorado        0.190765
         Idaho           0.114936
         Montana         0.132464
         Nevada          0.249196
         New Mexico      0.121898
         Utah            0.091199
         Wyoming         0.110630

**Subsetting the outer level with a list**

In [49]:
df_ind3.loc[["West South Central", "East South Central"]]

                                individuals  family_members  state_pop  \
region             state
West South Central Arkansas          2280.0           432.0    3009733
                   Louisiana         2540.0           519.0    4659690
                   Oklahoma          2823.0          1048.0    3940235
                   Texas            19199.0          6111.0   28628666
East South Central Alabama           2570.0           864.0    4887681
                   Kentucky          2735.0           953.0    4461153
                   Mississippi       1024.0           328.0    2981020
                   Tennessee         6139.0          1744.0    6771631

                                total_homeless  pct_homeless
region             state
West South Central Arkansas             2712.0      0.090108
                   Louisiana            3059.0      0.065648
                   Oklahoma             3871.0      0.098243
                   Texas               25310.0      0.088408
East South Central Alabama              3434.0      0.070258
                   Kentucky             3688.0      0.082669
                   Mississippi          1352.0      0.045354
                   Tennessee            7883.0      0.116412

**Subset Inner levels with a list of tuples**

In [50]:
df_ind3.tail()

,,individuals,family_members,state_pop,total_homeless,pct_homeless
region,state,,,,,
South Atlantic,Virginia,3928.0,2047.0,8501286,5975.0,0.070283
Pacific,Washington,16424.0,5880.0,7523869,22304.0,0.296443
South Atlantic,West Virginia,1021.0,222.0,1804291,1243.0,0.068891
East North Central,Wisconsin,2740.0,2167.0,5807406,4907.0,0.084496
Mountain,Wyoming,434.0,205.0,577601,639.0,0.110630

In [51]:
df_ind3.index

MultiIndex([('East South Central',              'Alabama'),
            (           'Pacific',               'Alaska'),
            (          'Mountain',              'Arizona'),
            ('West South Central',             'Arkansas'),
            (           'Pacific',           'California'),
            (          'Mountain',             'Colorado'),
            (       'New England',          'Connecticut'),
            (    'South Atlantic',             'Delaware'),
            (    'South Atlantic', 'District of Columbia'),
            (    'South Atlantic',              'Florida'),
            (    'South Atlantic',              'Georgia'),
            (           'Pacific',               'Hawaii'),
            (          'Mountain',                'Idaho'),
            ('East North Central',             'Illinois'),
            ('East North Central',              'Indiana'),
            ('West North Central',                 'Iowa'),
            ('West North Central',               'Kansas'),
            ('East South Central',             'Kentucky'),
            ('West South Central',            'Louisiana'),
            (       'New England',                'Maine'),
            (    'South Atlantic',             'Maryland'),
            (       'New England',        'Massachusetts'),
            ('East North Central',             'Michigan'),
            ('West North Central',            'Minnesota'),
            ('East South Central',          'Mississippi'),
            ('West North Central',             'Missouri'),
            (          'Mountain',              'Montana'),
            ('West North Central',             'Nebraska'),
            (          'Mountain',               'Nevada'),
            (       'New England',        'New Hampshire'),
            (      'Mid-Atlantic',           'New Jersey'),
            (          'Mountain',           'New Mexico'),
            (      'Mid-Atlantic',             'New York'),
            (    'South Atlantic',       'North Carolina'),
            ('West North Central',         'North Dakota'),
            ('East North Central',                 'Ohio'),
            ('West South Central',             'Oklahoma'),
            (           'Pacific',               'Oregon'),
            (      'Mid-Atlantic',         'Pennsylvania'),
            (       'New England',         'Rhode Island'),
            (    'South Atlantic',       'South Carolina'),
            ('West North Central',         'South Dakota'),
            ('East South Central',            'Tennessee'),
            ('West South Central',                'Texas'),
            (          'Mountain',                 'Utah'),
            (       'New England',              'Vermont'),
            (    'South Atlantic',             'Virginia'),
            (           'Pacific',           'Washington'),
            (    'South Atlantic',        'West Virginia'),
            ('East North Central',            'Wisconsin'),
            (          'Mountain',              'Wyoming')],
           names=['region', 'state'])

In [52]:
# Subsetting with multiindex
df_ind3.loc[[("New England", "Massachusetts"), ("West North Central", "Minnesota")]]

,,individuals,family_members,state_pop,total_homeless,pct_homeless
region,state,,,,,
New England,Massachusetts,6811.0,13257.0,6882635,20068.0,0.291574
West North Central,Minnesota,3993.0,3250.0,5606249,7243.0,0.129195

### Sorting by Index Values

In [53]:
df_ind3.sort_index()

                                         individuals  family_members  \
region             state
East North Central Illinois                   6752.0          3891.0
                   Indiana                    3776.0          1482.0
                   Michigan                   5209.0          3142.0
                   Ohio                       6929.0          3320.0
                   Wisconsin                  2740.0          2167.0
East South Central Alabama                    2570.0           864.0
                   Kentucky                   2735.0           953.0
                   Mississippi                1024.0           328.0
                   Tennessee                  6139.0          1744.0
Mid-Atlantic       New Jersey                 6048.0          3350.0
                   New York                  39827.0         52070.0
                   Pennsylvania               8163.0          5349.0
Mountain           Arizona                    7259.0          2606.0
                   Colorado                   7607.0          3250.0
                   Idaho                      1297.0           715.0
                   Montana                     983.0           422.0
                   Nevada                     7058.0           486.0
                   New Mexico                 1949.0           602.0
                   Utah                       1904.0           972.0
                   Wyoming                     434.0           205.0
New England        Connecticut                2280.0          1696.0
                   Maine                      1450.0          1066.0
                   Massachusetts              6811.0         13257.0
                   New Hampshire               835.0           615.0
                   Rhode Island                747.0           354.0
                   Vermont                     780.0           511.0
Pacific            Alaska                     1434.0           582.0
                   California               109008.0         20964.0
                   Hawaii                     4131.0          2399.0
                   Oregon                    11139.0          3337.0
                   Washington                16424.0          5880.0
South Atlantic     Delaware                    708.0           374.0
                   District of Columbia       3770.0          3134.0
                   Florida                   21443.0          9587.0
                   Georgia                    6943.0          2556.0
                   Maryland                   4914.0          2230.0
                   North Carolina             6451.0          2817.0
                   South Carolina             3082.0           851.0
                   Virginia                   3928.0          2047.0
                   West Virginia              1021.0           222.0
West North Central Iowa                       1711.0          1038.0
                   Kansas                     1443.0           773.0
                   Minnesota                  3993.0          3250.0
                   Missouri                   3776.0          2107.0
                   Nebraska                   1745.0           676.0
                   North Dakota                467.0            75.0
                   South Dakota                836.0           323.0
West South Central Arkansas                   2280.0           432.0
                   Louisiana                  2540.0           519.0
                   Oklahoma                   2823.0          1048.0
                   Texas                     19199.0          6111.0

                                         state_pop  total_homeless  \
region             state
East North Central Illinois               12723071         10643.0
                   Indiana                 6695497          5258.0
                   Michigan                9984072          8351.0
                   Ohio                   11676341         10249.0
                   Wisconsin               5807406          4907.0
East South Central Alabama                 4887681          3434.0
                   Kentucky                4461153          3688.0
                   Mississippi             2981020          1352.0
                   Tennessee               6771631          7883.0
Mid-Atlantic       New Jersey              8886025          9398.0
                   New York               19530351         91897.0
                   Pennsylvania           12800922         13512.0
Mountain           Arizona                 7158024          9865.0
                   Colorado                5691287         10857.0
                   Idaho                   1750536          2012.0
                   Montana                 1060665          1405.0
                   Nevada                  3027341          7544.0
                   New Mexico              2092741          2551.0
                   Utah                    3153550          2876.0
                   Wyoming                  577601           639.0
New England        Connecticut             3571520          3976.0
                   Maine                   1339057          2516.0
                   Massachusetts           6882635         20068.0
                   New Hampshire           1353465          1450.0
                   Rhode Island            1058287          1101.0
                   Vermont                  624358          1291.0
Pacific            Alaska                   735139          2016.0
                   California             39461588        129972.0
                   Hawaii                  1420593          6530.0
                   Oregon                  4181886         14476.0
                   Washington              7523869         22304.0
South Atlantic     Delaware                 965479          1082.0
                   District of Columbia     701547          6904.0
                   Florida                21244317         31030.0
                   Georgia                10511131          9499.0
                   Maryland                6035802          7144.0
                   North Carolina         10381615          9268.0
                   South Carolina          5084156          3933.0
                   Virginia                8501286          5975.0
                   West Virginia           1804291          1243.0
West North Central Iowa                    3148618          2749.0
                   Kansas                  2911359          2216.0
                   Minnesota               5606249          7243.0
                   Missouri                6121623          5883.0
                   Nebraska                1925614          2421.0
                   North Dakota             758080           542.0
                   South Dakota             878698          1159.0
West South Central Arkansas                3009733          2712.0
                   Louisiana               4659690          3059.0
                   Oklahoma                3940235          3871.0
                   Texas                  28628666         25310.0

                                         pct_homeless
region             state
East North Central Illinois                  0.083651
                   Indiana                   0.078530
                   Michigan                  0.083643
                   Ohio                      0.087776
                   Wisconsin                 0.084496
East South Central Alabama                   0.070258
                   Kentucky                  0.082669
                   Mississippi               0.045354
                   Tennessee                 0.116412
Mid-Atlantic       New Jersey                0.105762
                   New York                  0.470534
                   Pennsylvania              0.105555
Mountain           Arizona                   0.137817
                   Colorado                  0.190765
                   Idaho                     0.114936
                   Montana                   0.132464
                   Nevada                    0.249196
                   New Mexico                0.121898
                   Utah                      0.091199
                   Wyoming                   0.110630
New England        Connecticut               0.111325
                   Maine                     0.187893
                   Massachusetts             0.291574
                   New Hampshire             0.107132
                   Rhode Island              0.104036
                   Vermont                   0.206772
Pacific            Alaska                    0.274234
                   California                0.329363
                   Hawaii                    0.459667
                   Oregon                    0.346160
                   Washington                0.296443
South Atlantic     Delaware                  0.112069
                   District of Columbia      0.984111
                   Florida                   0.146063
                   Georgia                   0.090371
                   Maryland                  0.118360
                   North Carolina            0.089273
                   South Carolina            0.077358
                   Virginia                  0.070283
                   West Virginia             0.068891
West North Central Iowa                      0.087308
                   Kansas                    0.076116
                   Minnesota                 0.129195
                   Missouri                  0.096102
                   Nebraska                  0.125726
                   North Dakota              0.071496
                   South Dakota              0.131900
West South Central Arkansas                  0.090108
                   Louisiana                 0.065648
                   Oklahoma                  0.098243
                   Texas                     0.088408

**Controlling Sort Index**

In [54]:
df_ind3.sort_index(level=["region", "state"], ascending=[True, False])

# ascending = True: A-Z
# ascending = False: Z-A

                                         individuals  family_members  \
region             state
East North Central Wisconsin                  2740.0          2167.0
                   Ohio                       6929.0          3320.0
                   Michigan                   5209.0          3142.0
                   Indiana                    3776.0          1482.0
                   Illinois                   6752.0          3891.0
East South Central Tennessee                  6139.0          1744.0
                   Mississippi                1024.0           328.0
                   Kentucky                   2735.0           953.0
                   Alabama                    2570.0           864.0
Mid-Atlantic       Pennsylvania               8163.0          5349.0
                   New York                  39827.0         52070.0
                   New Jersey                 6048.0          3350.0
Mountain           Wyoming                     434.0           205.0
                   Utah                       1904.0           972.0
                   New Mexico                 1949.0           602.0
                   Nevada                     7058.0           486.0
                   Montana                     983.0           422.0
                   Idaho                      1297.0           715.0
                   Colorado                   7607.0          3250.0
                   Arizona                    7259.0          2606.0
New England        Vermont                     780.0           511.0
                   Rhode Island                747.0           354.0
                   New Hampshire               835.0           615.0
                   Massachusetts              6811.0         13257.0
                   Maine                      1450.0          1066.0
                   Connecticut                2280.0          1696.0
Pacific            Washington                16424.0          5880.0
                   Oregon                    11139.0          3337.0
                   Hawaii                     4131.0          2399.0
                   California               109008.0         20964.0
                   Alaska                     1434.0           582.0
South Atlantic     West Virginia              1021.0           222.0
                   Virginia                   3928.0          2047.0
                   South Carolina             3082.0           851.0
                   North Carolina             6451.0          2817.0
                   Maryland                   4914.0          2230.0
                   Georgia                    6943.0          2556.0
                   Florida                   21443.0          9587.0
                   District of Columbia       3770.0          3134.0
                   Delaware                    708.0           374.0
West North Central South Dakota                836.0           323.0
                   North Dakota                467.0            75.0
                   Nebraska                   1745.0           676.0
                   Missouri                   3776.0          2107.0
                   Minnesota                  3993.0          3250.0
                   Kansas                     1443.0           773.0
                   Iowa                       1711.0          1038.0
West South Central Texas                     19199.0          6111.0
                   Oklahoma                   2823.0          1048.0
                   Louisiana                  2540.0           519.0
                   Arkansas                   2280.0           432.0

                                         state_pop  total_homeless  \
region             state
East North Central Wisconsin               5807406          4907.0
                   Ohio                   11676341         10249.0
                   Michigan                9984072          8351.0
                   Indiana                 6695497          5258.0
                   Illinois               12723071         10643.0
East South Central Tennessee               6771631          7883.0
                   Mississippi             2981020          1352.0
                   Kentucky                4461153          3688.0
                   Alabama                 4887681          3434.0
Mid-Atlantic       Pennsylvania           12800922         13512.0
                   New York               19530351         91897.0
                   New Jersey              8886025          9398.0
Mountain           Wyoming                  577601           639.0
                   Utah                    3153550          2876.0
                   New Mexico              2092741          2551.0
                   Nevada                  3027341          7544.0
                   Montana                 1060665          1405.0
                   Idaho                   1750536          2012.0
                   Colorado                5691287         10857.0
                   Arizona                 7158024          9865.0
New England        Vermont                  624358          1291.0
                   Rhode Island            1058287          1101.0
                   New Hampshire           1353465          1450.0
                   Massachusetts           6882635         20068.0
                   Maine                   1339057          2516.0
                   Connecticut             3571520          3976.0
Pacific            Washington              7523869         22304.0
                   Oregon                  4181886         14476.0
                   Hawaii                  1420593          6530.0
                   California             39461588        129972.0
                   Alaska                   735139          2016.0
South Atlantic     West Virginia           1804291          1243.0
                   Virginia                8501286          5975.0
                   South Carolina          5084156          3933.0
                   North Carolina         10381615          9268.0
                   Maryland                6035802          7144.0
                   Georgia                10511131          9499.0
                   Florida                21244317         31030.0
                   District of Columbia     701547          6904.0
                   Delaware                 965479          1082.0
West North Central South Dakota             878698          1159.0
                   North Dakota             758080           542.0
                   Nebraska                1925614          2421.0
                   Missouri                6121623          5883.0
                   Minnesota               5606249          7243.0
                   Kansas                  2911359          2216.0
                   Iowa                    3148618          2749.0
West South Central Texas                  28628666         25310.0
                   Oklahoma                3940235          3871.0
                   Louisiana               4659690          3059.0
                   Arkansas                3009733          2712.0

                                         pct_homeless
region             state
East North Central Wisconsin                 0.084496
                   Ohio                      0.087776
                   Michigan                  0.083643
                   Indiana                   0.078530
                   Illinois                  0.083651
East South Central Tennessee                 0.116412
                   Mississippi               0.045354
                   Kentucky                  0.082669
                   Alabama                   0.070258
Mid-Atlantic       Pennsylvania              0.105555
                   New York                  0.470534
                   New Jersey                0.105762
Mountain           Wyoming                   0.110630
                   Utah                      0.091199
                   New Mexico                0.121898
                   Nevada                    0.249196
                   Montana                   0.132464
                   Idaho                     0.114936
                   Colorado                  0.190765
                   Arizona                   0.137817
New England        Vermont                   0.206772
                   Rhode Island              0.104036
                   New Hampshire             0.107132
                   Massachusetts             0.291574
                   Maine                     0.187893
                   Connecticut               0.111325
Pacific            Washington                0.296443
                   Oregon                    0.346160
                   Hawaii                    0.459667
                   California                0.329363
                   Alaska                    0.274234
South Atlantic     West Virginia             0.068891
                   Virginia                  0.070283
                   South Carolina            0.077358
                   North Carolina            0.089273
                   Maryland                  0.118360
                   Georgia                   0.090371
                   Florida                   0.146063
                   District of Columbia      0.984111
                   Delaware                  0.112069
West North Central South Dakota              0.131900
                   North Dakota              0.071496
                   Nebraska                  0.125726
                   Missouri                  0.096102
                   Minnesota                 0.129195
                   Kansas                    0.076116
                   Iowa                      0.087308
West South Central Texas                     0.088408
                   Oklahoma                  0.098243
                   Louisiana                 0.065648
                   Arkansas                  0.090108

# Assignment
- Understand the difference between `.loc` and `.iloc` in subsetting dataframes with Code.

In [59]:
df_ind3

                                         individuals  family_members  \
region             state
East South Central Alabama                    2570.0           864.0
Pacific            Alaska                     1434.0           582.0
Mountain           Arizona                    7259.0          2606.0
West South Central Arkansas                   2280.0           432.0
Pacific            California               109008.0         20964.0
Mountain           Colorado                   7607.0          3250.0
New England        Connecticut                2280.0          1696.0
South Atlantic     Delaware                    708.0           374.0
                   District of Columbia       3770.0          3134.0
                   Florida                   21443.0          9587.0
                   Georgia                    6943.0          2556.0
Pacific            Hawaii                     4131.0          2399.0
Mountain           Idaho                      1297.0           715.0
East North Central Illinois                   6752.0          3891.0
                   Indiana                    3776.0          1482.0
West North Central Iowa                       1711.0          1038.0
                   Kansas                     1443.0           773.0
East South Central Kentucky                   2735.0           953.0
West South Central Louisiana                  2540.0           519.0
New England        Maine                      1450.0          1066.0
South Atlantic     Maryland                   4914.0          2230.0
New England        Massachusetts              6811.0         13257.0
East North Central Michigan                   5209.0          3142.0
West North Central Minnesota                  3993.0          3250.0
East South Central Mississippi                1024.0           328.0
West North Central Missouri                   3776.0          2107.0
Mountain           Montana                     983.0           422.0
West North Central Nebraska                   1745.0           676.0
Mountain           Nevada                     7058.0           486.0
New England        New Hampshire               835.0           615.0
Mid-Atlantic       New Jersey                 6048.0          3350.0
Mountain           New Mexico                 1949.0           602.0
Mid-Atlantic       New York                  39827.0         52070.0
South Atlantic     North Carolina             6451.0          2817.0
West North Central North Dakota                467.0            75.0
East North Central Ohio                       6929.0          3320.0
West South Central Oklahoma                   2823.0          1048.0
Pacific            Oregon                    11139.0          3337.0
Mid-Atlantic       Pennsylvania               8163.0          5349.0
New England        Rhode Island                747.0           354.0
South Atlantic     South Carolina             3082.0           851.0
West North Central South Dakota                836.0           323.0
East South Central Tennessee                  6139.0          1744.0
West South Central Texas                     19199.0          6111.0
Mountain           Utah                       1904.0           972.0
New England        Vermont                     780.0           511.0
South Atlantic     Virginia                   3928.0          2047.0
Pacific            Washington                16424.0          5880.0
South Atlantic     West Virginia              1021.0           222.0
East North Central Wisconsin                  2740.0          2167.0
Mountain           Wyoming                     434.0           205.0

                                         state_pop  total_homeless  \
region             state
East South Central Alabama                 4887681          3434.0
Pacific            Alaska                   735139          2016.0
Mountain           Arizona                 7158024          9865.0
West South Central Arkansas                3009733          2712.0
Pacific            California             39461588        129972.0
Mountain           Colorado                5691287         10857.0
New England        Connecticut             3571520          3976.0
South Atlantic     Delaware                 965479          1082.0
                   District of Columbia     701547          6904.0
                   Florida                21244317         31030.0
                   Georgia                10511131          9499.0
Pacific            Hawaii                  1420593          6530.0
Mountain           Idaho                   1750536          2012.0
East North Central Illinois               12723071         10643.0
                   Indiana                 6695497          5258.0
West North Central Iowa                    3148618          2749.0
                   Kansas                  2911359          2216.0
East South Central Kentucky                4461153          3688.0
West South Central Louisiana               4659690          3059.0
New England        Maine                   1339057          2516.0
South Atlantic     Maryland                6035802          7144.0
New England        Massachusetts           6882635         20068.0
East North Central Michigan                9984072          8351.0
West North Central Minnesota               5606249          7243.0
East South Central Mississippi             2981020          1352.0
West North Central Missouri                6121623          5883.0
Mountain           Montana                 1060665          1405.0
West North Central Nebraska                1925614          2421.0
Mountain           Nevada                  3027341          7544.0
New England        New Hampshire           1353465          1450.0
Mid-Atlantic       New Jersey              8886025          9398.0
Mountain           New Mexico              2092741          2551.0
Mid-Atlantic       New York               19530351         91897.0
South Atlantic     North Carolina         10381615          9268.0
West North Central North Dakota             758080           542.0
East North Central Ohio                   11676341         10249.0
West South Central Oklahoma                3940235          3871.0
Pacific            Oregon                  4181886         14476.0
Mid-Atlantic       Pennsylvania           12800922         13512.0
New England        Rhode Island            1058287          1101.0
South Atlantic     South Carolina          5084156          3933.0
West North Central South Dakota             878698          1159.0
East South Central Tennessee               6771631          7883.0
West South Central Texas                  28628666         25310.0
Mountain           Utah                    3153550          2876.0
New England        Vermont                  624358          1291.0
South Atlantic     Virginia                8501286          5975.0
Pacific            Washington              7523869         22304.0
South Atlantic     West Virginia           1804291          1243.0
East North Central Wisconsin               5807406          4907.0
Mountain           Wyoming                  577601           639.0

                                         pct_homeless
region             state
East South Central Alabama                   0.070258
Pacific            Alaska                    0.274234
Mountain           Arizona                   0.137817
West South Central Arkansas                  0.090108
Pacific            California                0.329363
Mountain           Colorado                  0.190765
New England        Connecticut               0.111325
South Atlantic     Delaware                  0.112069
                   District of Columbia      0.984111
                   Florida                   0.146063
                   Georgia                   0.090371
Pacific            Hawaii                    0.459667
Mountain           Idaho                     0.114936
East North Central Illinois                  0.083651
                   Indiana                   0.078530
West North Central Iowa                      0.087308
                   Kansas                    0.076116
East South Central Kentucky                  0.082669
West South Central Louisiana                 0.065648
New England        Maine                     0.187893
South Atlantic     Maryland                  0.118360
New England        Massachusetts             0.291574
East North Central Michigan                  0.083643
West North Central Minnesota                 0.129195
East South Central Mississippi               0.045354
West North Central Missouri                  0.096102
Mountain           Montana                   0.132464
West North Central Nebraska                  0.125726
Mountain           Nevada                    0.249196
New England        New Hampshire             0.107132
Mid-Atlantic       New Jersey                0.105762
Mountain           New Mexico                0.121898
Mid-Atlantic       New York                  0.470534
South Atlantic     North Carolina            0.089273
West North Central North Dakota              0.071496
East North Central Ohio                      0.087776
West South Central Oklahoma                  0.098243
Pacific            Oregon                    0.346160
Mid-Atlantic       Pennsylvania              0.105555
New England        Rhode Island              0.104036
South Atlantic     South Carolina            0.077358
West North Central South Dakota              0.131900
East South Central Tennessee                 0.116412
West South Central Texas                     0.088408
Mountain           Utah                      0.091199
New England        Vermont                   0.206772
South Atlantic     Virginia                  0.070283
Pacific            Washington                0.296443
South Atlantic     West Virginia             0.068891
East North Central Wisconsin                 0.084496
Mountain           Wyoming                   0.110630

In [ ]:
df_ind3.iloc[30]

individuals       6.048000e+03
family_members    3.350000e+03
state_pop         8.886025e+06
total_homeless    9.398000e+03
pct_homeless      1.057616e-01
Name: (Mid-Atlantic, New Jersey), dtype: float64